# Generated by Django 5.1.5 on 2025-01-17 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_user_first_name_remove_user_last_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('level', models.CharField(max_length=50)),
                ('grammar', models.IntegerField()),
                ('grammar_total', models.IntegerField(default=40)),
                ('vocabulary', models.IntegerField()),
                ('vocabulary_total', models.IntegerField(default=20)),
                ('reading', models.IntegerField()),
                ('reading_total', models.IntegerField(default=20)),
                ('writing', models.IntegerField()),
                ('writing_total', models.IntegerField(default=20)),
                ('listening', models.IntegerField()),
                ('listening_total', models.IntegerField(default=20)),
                ('speaking', models.IntegerField()),
                ('speaking_total', models.IntegerField(default=20)),
                ('teacher_assessment', models.IntegerField()),
                ('teacher_assessment_total', models.IntegerField(default=10)),
                ('total_score', models.IntegerField()),
                ('total_score_out_of', models.IntegerField(default=150)),
                ('total_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('attendance', models.CharField(max_length=20)),
                ('attendance_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('teacher_recommendation', models.CharField(choices=[('Repeat', 'Repeat'), ('Progress', 'Progress')], max_length=50)),
                ('teacher_signed', models.CharField(blank=True, max_length=255, null=True)),
                ('director_signed', models.CharField(blank=True, max_length=255, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_results', to='app.student')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_results', to='app.teacher')),
            ],
            options={
                'verbose_name': 'Exam Result',
                'verbose_name_plural': 'Exam Results',
            },
        ),
    ]
