# Generated by Django 5.1.5 on 2025-01-17 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_examresult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examresult',
            name='total_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='examresult',
            name='total_score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
