# Generated by Django 5.1.5 on 2025-01-17 13:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_courselevel_alter_examresult_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='esignature',
            field=models.ImageField(default=1, upload_to='signatures/'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ManagingDirector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('esignature', models.ImageField(upload_to='signatures/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='director_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
