# Generated by Django 5.1.5 on 2025-01-17 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_teacher_esignature_managingdirector'),
    ]

    operations = [
        migrations.AddField(
            model_name='examresult',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='exam_results_pdfs/'),
        ),
    ]
