# Generated by Django 5.1.5 on 2025-01-17 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_examresult_pdf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examresult',
            name='director_signed',
        ),
        migrations.RemoveField(
            model_name='examresult',
            name='teacher_signed',
        ),
        migrations.AddField(
            model_name='examresult',
            name='units_covered',
            field=models.CharField(default=1, max_length=20, verbose_name='eg. 1 To 5'),
            preserve_default=False,
        ),
    ]
