# Generated by Django 5.1.5 on 2025-01-21 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_remove_examresult_director_signed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examresult',
            name='teacher_recommendation',
            field=models.CharField(choices=[('Repeat', 'Repeat'), ('Progress', 'Progress'), ('Marginal Pass', 'Marginal Pass'), ('Conditional Pass', 'Conditional Pass')], max_length=50),
        ),
        migrations.AlterField(
            model_name='examresult',
            name='units_covered',
            field=models.CharField(max_length=20, verbose_name='Unites Covered e.g. (1 To 5)'),
        ),
    ]
