# Generated by Django 5.1.5 on 2025-01-21 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_examresult_teacher_recommendation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='courselevel',
            name='month',
            field=models.CharField(choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='courselevel',
            name='year',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
