# Generated by Django 5.1.5 on 2025-01-21 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_courselevel_month_courselevel_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courselevel',
            name='year',
            field=models.IntegerField(verbose_name='Level Year'),
        ),
    ]
