# Generated by Django 5.1.5 on 2025-01-21 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_courselevel_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courselevel',
            name='month',
            field=models.CharField(choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')], max_length=50, verbose_name='Level Month'),
        ),
    ]
