# Generated by Django 5.1.5 on 2025-02-07 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_student_level'),
    ]

    operations = [
        migrations.RenameField(
            model_name='examresult',
            old_name='date',
            new_name='date_of_creation',
        ),
    ]
