# Generated by Django 5.1.5 on 2025-02-07 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_rename_date_examresult_date_of_creation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examresult',
            name='attendance',
        ),
        migrations.AddField(
            model_name='examresult',
            name='note',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
