# Generated by Django 5.1.5 on 2025-02-10 12:44

import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_student_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='country',
            field=django_countries.fields.CountryField(max_length=2),
        ),
    ]
