# Generated by Django 5.1.5 on 2025-02-11 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_alter_user_is_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courselevel',
            name='month',
        ),
        migrations.RemoveField(
            model_name='courselevel',
            name='year',
        ),
    ]
