# Generated by Django 5.1.5 on 2025-02-12 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_remove_courselevel_month_remove_courselevel_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examresult',
            name='note',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
