# Generated by Django 5.1.5 on 2025-02-12 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_systemsettings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='systemsettings',
            old_name='counter_start',
            new_name='student_id_counter_start',
        ),
    ]
