# Generated by Django 5.1.5 on 2025-02-20 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_alter_student_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_approved',
            field=models.BooleanField(default=True),
        ),
    ]
