# Generated by Django 5.1.5 on 2025-03-08 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_user_first_name_user_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examresult',
            name='grammar',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='examresult',
            name='grammar_total',
            field=models.DecimalField(decimal_places=2, default=40, max_digits=5),
        ),
        migrations.AlterField(
            model_name='examresult',
            name='listening',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='examresult',
            name='listening_total',
            field=models.DecimalField(decimal_places=2, default=20, max_digits=5),
        ),
        migrations.AlterField(
            model_name='examresult',
            name='reading',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='examresult',
            name='reading_total',
            field=models.DecimalField(decimal_places=2, default=20, max_digits=5),
        ),
        migrations.AlterField(
            model_name='examresult',
            name='speaking',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='examresult',
            name='speaking_total',
            field=models.DecimalField(decimal_places=2, default=20, max_digits=5),
        ),
        migrations.AlterField(
            model_name='examresult',
            name='teacher_assessment',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='examresult',
            name='teacher_assessment_total',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=5),
        ),
        migrations.AlterField(
            model_name='examresult',
            name='total_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='examresult',
            name='total_score_out_of',
            field=models.DecimalField(decimal_places=2, default=150, max_digits=5),
        ),
        migrations.AlterField(
            model_name='examresult',
            name='vocabulary',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='examresult',
            name='vocabulary_total',
            field=models.DecimalField(decimal_places=2, default=20, max_digits=5),
        ),
        migrations.AlterField(
            model_name='examresult',
            name='writing',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='examresult',
            name='writing_total',
            field=models.DecimalField(decimal_places=2, default=20, max_digits=5),
        ),
    ]
